web:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - ./src/:/app/
  links:
    - postgres
    - redis
postgres:
  image: postgres:9.6-alpine
  volumes:
    - ./postgresql_data:/var/lib/postgresql/data
  ports:
    - "5432"
redis:
  image: redis:3.2.9
  ports:
    - "6379"
