default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  url: postgresql://postgres/messaging_development?pool=5
test:
  <<: *default
  url: postgresql://postgres/messaging_test?pool=5
production:
  <<: *default
  database: messaging_production
